# Generated by Django 5.2 on 2025-04-21 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='appointment_notes',
        ),
        migrations.RenameField(
            model_name='vaccination',
            old_name='notes',
            new_name='vaccination_notes',
        ),
    ]
