# Generated by Django 5.2 on 2025-04-21 07:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0003_rename_name_vaccination_vaccination_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='scheduled_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Scheduled', max_length=20),
        ),
    ]
